export const mock = {
  rows: [
    {
      project_task_id: 122820,
      space_id_id: 50655,
      space_id: "TYO5-4-1-S-001-0306",
      space_other_name: "W4AN-E2-6",
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000122820",
      product_code: "CAB050C.RC",
      location_id: 12,
      location_name: "TYO5",
      product_name: "(CTC Only) 19'' Cabinet Reservation",
      product_attribute: "",
      sales_order_name: "ITCJP-OR-007297",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: "W4AN-E2-6",
      order_date: "19/09/2023",
      request_date: "01/10/2023",
      installed_date: "",
      contract_end_date: "30/09/2024",
    },
    {
      project_task_id: 122819,
      space_id_id: 50654,
      space_id: "TYO5-4-1-S-001-0305",
      space_other_name: "W4AN-E2-5",
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000122819",
      product_code: "CAB050C.RC",
      location_id: 12,
      location_name: "TYO5",
      product_name: "(CTC Only) 19'' Cabinet Reservation",
      product_attribute: "",
      sales_order_name: "ITCJP-OR-007297",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: "W4AN-E2-5",
      order_date: "19/09/2023",
      request_date: "01/10/2023",
      installed_date: "",
      contract_end_date: "30/09/2024",
    },
    {
      project_task_id: 122843,
      space_id_id: 50678,
      space_id: "TYO5-4-1-S-001-0506",
      space_other_name: "W4AN-E4-6",
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000122843",
      product_code: "CAB050C.RC",
      location_id: 12,
      location_name: "TYO5",
      product_name: "(CTC Only) 19'' Cabinet Reservation",
      product_attribute: "",
      sales_order_name: "ITCJP-OR-007297",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: "W4AN-E4-6",
      order_date: "19/09/2023",
      request_date: "01/10/2023",
      installed_date: "",
      contract_end_date: "30/09/2024",
    },
    {
      project_task_id: 125826,
      space_id_id: 50783,
      space_id: "TYO6-2-3-S-001-0612Y",
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000125826",
      product_code: "CAB003C.RC",
      location_id: 13,
      location_name: "TYO6",
      product_name: '(CTC only) 19" Cabinet - Half',
      product_attribute: "Draw Cap in kVA: 0kVA",
      sales_order_name: "ITCJP-OR-003893-SO1",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "10/11/2023",
      request_date: "02/12/2023",
      installed_date: "",
      contract_end_date: "30/11/2022",
    },
    {
      project_task_id: 122844,
      space_id_id: 50679,
      space_id: "TYO5-4-1-S-001-0507",
      space_other_name: "W4AN-E4-7",
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000122844",
      product_code: "CAB050C.RC",
      location_id: 12,
      location_name: "TYO5",
      product_name: "(CTC Only) 19'' Cabinet Reservation",
      product_attribute: "",
      sales_order_name: "ITCJP-OR-007297",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: "W4AN-E4-7",
      order_date: "19/09/2023",
      request_date: "01/10/2023",
      installed_date: "",
      contract_end_date: "30/09/2024",
    },
    {
      project_task_id: 122821,
      space_id_id: 50656,
      space_id: "TYO5-4-1-S-001-0307",
      space_other_name: "W4AN-E2-7",
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000122821",
      product_code: "CAB050C.RC",
      location_id: 12,
      location_name: "TYO5",
      product_name: "(CTC Only) 19'' Cabinet Reservation",
      product_attribute: "",
      sales_order_name: "ITCJP-OR-007297",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: "W4AN-E2-7",
      order_date: "19/09/2023",
      request_date: "01/10/2023",
      installed_date: "",
      contract_end_date: "30/09/2024",
    },
    {
      project_task_id: 105806,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000105806",
      product_code: "OFC001.RC",
      location_id: 4,
      location_name: "TYO1",
      product_name: "Back Office",
      product_attribute: "Draw Cap in kVA: 0kVA",
      sales_order_name: "ITCJP-OR-003905",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Admin",
      legacy_number: null,
      cs_reference: null,
      order_date: "30/10/2022",
      request_date: "",
      installed_date: "",
      contract_end_date: "30/11/2022",
    },
    {
      project_task_id: 105805,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000105805",
      product_code: "OFC001.RC",
      location_id: 13,
      location_name: "TYO6",
      product_name: "Back Office",
      product_attribute: "Draw Cap in kVA: 0kVA",
      sales_order_name: "ITCJP-OR-003908",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Admin",
      legacy_number: null,
      cs_reference: null,
      order_date: "30/10/2022",
      request_date: "",
      installed_date: "",
      contract_end_date: "30/11/2022",
    },
    {
      project_task_id: 105803,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000105803",
      product_code: "OFC001.RC",
      location_id: 11,
      location_name: "TYO4",
      product_name: "Back Office",
      product_attribute: "Draw Cap in kVA: 0kVA",
      sales_order_name: "ITCJP-OR-003906",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Admin",
      legacy_number: null,
      cs_reference: null,
      order_date: "30/10/2022",
      request_date: "",
      installed_date: "",
      contract_end_date: "30/11/2022",
    },
    {
      project_task_id: 127127,
      space_id_id: 50853,
      space_id: "TYO6-3-3-S-001-0808",
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ITCJP-IB-000127127",
      product_code: "CAB050C.RC",
      location_id: 13,
      location_name: "TYO6",
      product_name: "(CTC Only) 19'' Cabinet Reservation",
      product_attribute: "",
      sales_order_name: "ITCJP-OR-003894-SO24",
      qty: 1,
      po_number: null,
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "01/11/2023",
      request_date: "31/03/2024",
      installed_date: "",
      contract_end_date: "30/11/2022",
    },
  ],
  count: 10,
  page: 1,
  pageSize: 11,
  filter: [
    { name: "status", value: "in service" },
    { name: "category_name", value: "CAB|POW0|CAG|OFC|RMH" },
  ],
  sort: "installed_date",
  sortDir: "desc",
  total: 104,
};
