export const mock = {
  rows: [
    {
      project_task_id: 105714,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000105714",
      product_code: "POW001.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "AC Single Phase 105Volt Primary",
      product_attribute: "Amps: 20Amps",
      sales_order_name: "ARNJP-OR-005582",
      qty: 1,
      po_number: "9900006354",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "31/03/2023",
      request_date: "09/06/2023",
      installed_date: "",
      contract_end_date: "30/04/2024",
    },
    {
      project_task_id: 105710,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000105710",
      product_code: "POW011.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "AC Single Phase 105Volt Redundant",
      product_attribute: "Amps: 20Amps",
      sales_order_name: "ARNJP-OR-005554",
      qty: 1,
      po_number: "9900005983",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "30/03/2023",
      request_date: "28/07/2023",
      installed_date: "",
      contract_end_date: "30/03/2024",
    },
    {
      project_task_id: 105708,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000105708",
      product_code: "POW001.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "AC Single Phase 105Volt Primary",
      product_attribute: "Amps: 20Amps",
      sales_order_name: "ARNJP-OR-005554",
      qty: 1,
      po_number: "9900005983",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "30/03/2023",
      request_date: "28/07/2023",
      installed_date: "",
      contract_end_date: "30/03/2024",
    },
    {
      project_task_id: 105716,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000105716",
      product_code: "POW011.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "AC Single Phase 105Volt Redundant",
      product_attribute: "Amps: 20Amps",
      sales_order_name: "ARNJP-OR-005582",
      qty: 1,
      po_number: "9900006354",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "31/03/2023",
      request_date: "09/06/2023",
      installed_date: "",
      contract_end_date: "30/04/2024",
    },
    {
      project_task_id: 129987,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000129987",
      product_code: "POW031.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "DC -48V Redundant",
      product_attribute: "",
      sales_order_name: "ARNJP-OR-009051",
      qty: 1,
      po_number: "9900010761",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "25/01/2024",
      request_date: "19/04/2024",
      installed_date: "15/04/2024",
      contract_end_date: "18/04/2025",
    },
    {
      project_task_id: 129985,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000129985",
      product_code: "POW021.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "DC -48V Primary",
      product_attribute: "",
      sales_order_name: "ARNJP-OR-009051",
      qty: 1,
      po_number: "9900010761",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "25/01/2024",
      request_date: "19/04/2024",
      installed_date: "15/04/2024",
      contract_end_date: "18/04/2025",
    },
    {
      project_task_id: 129989,
      space_id_id: 30858,
      space_id: "TYO2-5-1-S-001-0201",
      space_other_name: "CS1-11025AR61",
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000129989",
      product_code: "CAB001.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: '19" Cabinet',
      product_attribute: "Draw Cap in kVA: 2kVA",
      sales_order_name: "ARNJP-OR-009051",
      qty: 1,
      po_number: "9900010761",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "25/01/2024",
      request_date: "19/04/2024",
      installed_date: "15/04/2024",
      contract_end_date: "18/04/2025",
    },
    {
      project_task_id: 129877,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000129877",
      product_code: "POW021.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "DC -48V Primary",
      product_attribute: "",
      sales_order_name: "ARNJP-OR-007710-CO3",
      qty: 1,
      po_number: "9900010699",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "19/03/2024",
      request_date: "19/04/2024",
      installed_date: "15/04/2024",
      contract_end_date: "01/10/2024",
    },
    {
      project_task_id: 129879,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000129879",
      product_code: "POW031.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "DC -48V Redundant",
      product_attribute: "",
      sales_order_name: "ARNJP-OR-007710-CO3",
      qty: 1,
      po_number: "9900010699",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "19/03/2024",
      request_date: "19/04/2024",
      installed_date: "14/04/2024",
      contract_end_date: "01/10/2024",
    },
    {
      project_task_id: 128380,
      space_id_id: null,
      space_id: null,
      space_other_name: null,
      end_customer_id: null,
      end_customer: null,
      service_name: "ARNJP-IB-000128380",
      product_code: "POW031.RC",
      location_id: 6,
      location_name: "TYO2",
      product_name: "DC -48V Redundant",
      product_attribute: "",
      sales_order_name: "ARNJP-OR-004852-CO5",
      qty: 1,
      po_number: "9900010113",
      status: "In Service",
      created_by: "Kaoru Takano",
      legacy_number: null,
      cs_reference: null,
      order_date: "06/02/2024",
      request_date: "01/03/2024",
      installed_date: "08/03/2024",
      contract_end_date: "30/03/2024",
    },
  ],
  count: 10,
  page: 1,
  pageSize: 1,
  filter: [
    { name: "status", value: "in service" },
    { name: "category_name", value: "CAB|POW0|CAG|OFC|RMH" },
  ],
  sort: "installed_date",
  sortDir: "desc",
  total: 55,
};
